INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Basic Portfolio', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Enhanced Portfolio', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Hangman', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Psychic Game', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Crystal Collector Game', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Star Wars RPG', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Basic Trivia', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Advanced Trivia', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Giftastic', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Rock Paper Scissors', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Train Scheduler', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Liri Bot', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Flashcards', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Bamazon', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Friend Finder', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Eat Da Burger', 'front', 5, 1, 'html', null, 'employment');
INSERT INTO picker (project, whatType, duration, whatGroup, whatLanguage, technology, interests, difficulty) VALUES ('Burger Sequel', 'front', 5, 1, 'html', null, 'employment');